// Approve-then-send email. Drafts are generated by the LLM and stored in the `emails` collection;
// nothing goes out until POST /api/emails/:id/send. SMTP via nodemailer (Gmail app password works).
import nodemailer from 'nodemailer'
import { getDoc, putDoc, patchDoc, uid, getSettings } from './db.js'
import { chat } from './llm.js'

export interface Email {
  id: string; kind: 'invoice_reminder' | 'invoice_demand' | 'investor_update' | 'assignment' | 'custom'
  to: string; subject: string; body: string; status: 'draft' | 'sent' | 'failed'
  refId?: string; createdAt: string; sentAt?: string; error?: string; source: string
}

export const smtpConfigured = () => !!(process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS)

function transport() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT ?? 587), secure: process.env.SMTP_SECURE === 'true',
    auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
  })
}

export function createDraft(e: Omit<Email, 'id' | 'status' | 'createdAt'>): Email {
  const doc: Email = { id: uid(), status: 'draft', createdAt: new Date().toISOString(), ...e }
  putDoc('emails', doc.id, doc as unknown as Record<string, unknown>)
  return doc
}

export async function draftWithLLM(kind: Email['kind'], to: string, brief: string, refId?: string, source = 'automation'): Promise<Email> {
  const s = getSettings()
  const text = await chat({
    system: `You write concise, professional business emails on behalf of ${s.founderName}, founder/CEO of a small services company in Pakistan. Currency PKR. Plain text only, no markdown. Return JSON: {"subject": string, "body": string}. End the body with this signature exactly:\n${s.email.signature}`,
    user: brief, json: true, temperature: 0.3,
  })
  let subject = 'Update', body = text
  try { const j = JSON.parse(text); subject = j.subject ?? subject; body = j.body ?? body } catch { /* keep raw */ }
  return createDraft({ kind, to, subject, body, refId, source })
}

export async function sendEmail(id: string): Promise<Email> {
  const doc = getDoc<Email>('emails', id)?.data
  if (!doc) throw new Error('Email not found')
  if (doc.status === 'sent') return doc
  if (!smtpConfigured()) throw new Error('SMTP not configured on the server (set SMTP_HOST/SMTP_USER/SMTP_PASS)')
  const s = getSettings()
  try {
    await transport().sendMail({ from: s.email.from || process.env.SMTP_USER, to: doc.to, subject: doc.subject, text: doc.body })
    patchDoc('emails', id, { status: 'sent', sentAt: new Date().toISOString(), error: undefined })
  } catch (e) {
    patchDoc('emails', id, { status: 'failed', error: (e as Error).message })
    throw e
  }
  return getDoc<Email>('emails', id)!.data
}
